services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  lab-framework-demo:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer
    # folder. Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build:
      context: .
      dockerfile: ./Dockerfile
    # image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mock-server
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    build:
      context: ..
      dockerfile: ./Dockerfile.redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  mock-server:
    image: mockserver/mockserver
    ports:
      - "80:1080" # for UDF mocks
      - "5123:1080" # for petname service mocks

volumes:
  cache:
    driver: local

networks:
  default:
    name: lab-framework
    driver: bridge
